language: objective-c

osx_image: xcode8
xcode_sdk: iphonesimulator10.0

script:
- xcodebuild clean build test -workspace DKImagePickerControllerDemo.xcworkspace -scheme DKImagePickerControllerDemo -destination "platform=iOS,name=iPhone 6s"